FROM node:22.19.0-bookworm-slim

WORKDIR /opt/lexicon-authority
COPY e2e/atmosphere/package.json package.json
COPY e2e/atmosphere/package-lock.json package-lock.json
RUN npm ci --ignore-scripts --omit=dev

USER node
