/**
 * Observability helpers for Caddy's on-demand TLS ask endpoint.
 *
 * Caddy calls `/tls-check` during TLS handshakes for hostnames it does not
 * already have certificates for. When that path slows down, Caddy can build up
 * pending handshakes before ordinary HTTP access logs exist. This module keeps
 * lightweight aggregate counters and targeted slow/aborted logs so operators
 * can reconstruct future incidents without enabling noisy per-request tracing.
 */
import { monitorEventLoopDelay, performance } from 'node:perf_hooks'
import type { IntervalHistogram } from 'node:perf_hooks'

/** Classification used to group `/tls-check` requests without logging every hostname. */
export type TlsCheckDomainClass =
  | 'missing'
  | 'apex'
  | 'auth'
  | 'oneLabel'
  | 'nested'
  | 'unsupported'

/** Hostname settings needed to classify a Caddy TLS permission check. */
export interface TlsCheckClassifierOptions {
  /** Public PDS hostname, such as `climateai.org`, which is always allowed. */
  pdsHostname: string
  /** Auth-service hostname, such as `auth.climateai.org`, which is always allowed. */
  authHostname: string
  /** Hosted handle suffixes from the PDS identity config, such as `.climateai.org`. */
  serviceHandleDomains: readonly string[]
}

/** Structured logger methods used by the TLS-check observer. */
export interface TlsCheckLogger {
  /** Write an informational aggregate event. */
  info(fields: Record<string, unknown>, message: string): void
  /** Write an actionable warning for an unusually slow or aborted request. */
  warn(fields: Record<string, unknown>, message: string): void
}

/** Runtime options for `TlsCheckObserver`. */
export interface TlsCheckObserverOptions {
  /** Logger that receives aggregate, slow-request, and aborted-request events. */
  logger: TlsCheckLogger
  /** Hostname settings used to classify each request. */
  classifier: TlsCheckClassifierOptions
  /** Milliseconds between aggregate summary logs. Defaults to 10 seconds. */
  summaryIntervalMs?: number
  /** Request duration in milliseconds that emits an individual slow log. Defaults to 1000 ms. */
  slowRequestMs?: number
  /** Maximum individual slow/aborted/failed logs per category in each summary window. Defaults to 50. */
  individualLogLimitPerWindow?: number
  /** Event-loop monitor resolution in milliseconds. Defaults to 20 ms. */
  eventLoopResolutionMs?: number
  /** Enables event-loop lag metrics in summary logs. Defaults to true. */
  enableEventLoopMonitor?: boolean
  /** Clock used for duration measurements. Defaults to `performance.now()`. */
  nowMs?: () => number
}

/** Per-request handle returned by `TlsCheckObserver.begin()`. */
export interface TlsCheckRequestScope {
  /** Record the duration of the account lookup portion of the request. */
  recordAccountLookup(durationMs: number): void
  /** Mark the request as completed with the HTTP status that Express sent. */
  complete(statusCode: number): void
  /** Mark the request as aborted before Express completed the response. */
  abort(): void
  /** Mark the request as failed before Express completed the response. */
  fail(err: unknown): void
}

type IndividualLogCategory = 'slow' | 'aborted' | 'failed'

type MutableWindowMetrics = {
  started: number
  completed: number
  aborted: number
  failed: number
  inflight: number
  maxInflight: number
  status: Map<number, number>
  domainClass: Map<TlsCheckDomainClass, number>
  durationsMs: number[]
  accountLookupMs: number[]
  individualLogEmitted: Map<IndividualLogCategory, number>
  individualLogSuppressed: Map<IndividualLogCategory, number>
}

const DEFAULT_SUMMARY_INTERVAL_MS = 10_000
const DEFAULT_SLOW_REQUEST_MS = 1_000
const DEFAULT_EVENT_LOOP_RESOLUTION_MS = 20
const DEFAULT_INDIVIDUAL_LOG_LIMIT_PER_WINDOW = 50

/**
 * Classify a requested TLS hostname into the buckets operators need during
 * incident review. Use this when deciding whether a spike is made of legitimate
 * one-label handles or nested garbage hostnames generated by scanners.
 */
export function classifyTlsCheckDomain(
  domain: string | undefined,
  opts: TlsCheckClassifierOptions,
): TlsCheckDomainClass {
  if (!domain) {
    return 'missing'
  }
  if (domain === opts.pdsHostname) {
    return 'apex'
  }
  if (domain === opts.authHostname) {
    return 'auth'
  }

  const matchedHandleDomain = opts.serviceHandleDomains.find((suffix) =>
    domain.endsWith(suffix),
  )
  if (!matchedHandleDomain) {
    return 'unsupported'
  }

  const localPart = domain.slice(0, domain.length - matchedHandleDomain.length)
  if (!localPart || localPart.includes('.')) {
    return 'nested'
  }
  return 'oneLabel'
}

/**
 * Tracks `/tls-check` load and emits periodic aggregate logs plus targeted
 * slow/aborted request logs. The observer is intentionally self-contained so it
 * can be stopped cleanly during shutdown and exercised in unit tests.
 */
export class TlsCheckObserver {
  private readonly logger: TlsCheckLogger
  private readonly classifier: TlsCheckClassifierOptions
  private readonly slowRequestMs: number
  private readonly individualLogLimitPerWindow: number
  private readonly nowMs: () => number
  private readonly eventLoopMonitor?: IntervalHistogram
  private readonly summaryTimer?: ReturnType<typeof setInterval>
  private metrics = createEmptyMetrics()

  constructor(opts: TlsCheckObserverOptions) {
    this.logger = opts.logger
    this.classifier = opts.classifier
    this.slowRequestMs = opts.slowRequestMs ?? DEFAULT_SLOW_REQUEST_MS
    this.individualLogLimitPerWindow =
      opts.individualLogLimitPerWindow ??
      DEFAULT_INDIVIDUAL_LOG_LIMIT_PER_WINDOW
    this.nowMs = opts.nowMs ?? (() => performance.now())

    if (opts.enableEventLoopMonitor !== false) {
      this.eventLoopMonitor = monitorEventLoopDelay({
        resolution:
          opts.eventLoopResolutionMs ?? DEFAULT_EVENT_LOOP_RESOLUTION_MS,
      })
      this.eventLoopMonitor.enable()
    }

    const summaryIntervalMs =
      opts.summaryIntervalMs ?? DEFAULT_SUMMARY_INTERVAL_MS
    if (summaryIntervalMs > 0) {
      this.summaryTimer = setInterval(() => {
        this.flush()
      }, summaryIntervalMs)
      this.summaryTimer.unref()
    }
  }

  /** Begin tracking one `/tls-check` request and return its completion handle. */
  begin(domain: string | undefined): TlsCheckRequestScope {
    const startedAtMs = this.nowMs()
    const domainClass = classifyTlsCheckDomain(domain, this.classifier)
    this.metrics.started += 1
    this.metrics.inflight += 1
    this.metrics.maxInflight = Math.max(
      this.metrics.maxInflight,
      this.metrics.inflight,
    )
    incrementMap(this.metrics.domainClass, domainClass)

    let ended = false
    const finish = (status: 'completed' | 'aborted' | 'failed') => {
      if (ended) {
        return undefined
      }
      ended = true
      const durationMs = Math.max(0, this.nowMs() - startedAtMs)
      const currentMetrics = this.metrics
      currentMetrics.inflight = Math.max(0, currentMetrics.inflight - 1)
      if (status === 'completed') {
        currentMetrics.completed += 1
        currentMetrics.durationsMs.push(durationMs)
      } else if (status === 'aborted') {
        currentMetrics.aborted += 1
      } else {
        currentMetrics.failed += 1
      }
      return durationMs
    }

    return {
      recordAccountLookup: (durationMs: number) => {
        if (!ended && Number.isFinite(durationMs) && durationMs >= 0) {
          this.metrics.accountLookupMs.push(durationMs)
        }
      },
      complete: (statusCode: number) => {
        const durationMs = finish('completed')
        if (durationMs === undefined) {
          return
        }
        incrementMap(this.metrics.status, statusCode)
        if (durationMs >= this.slowRequestMs) {
          this.warnWithinWindow(
            'slow',
            {
              domain,
              domainClass,
              durationMs: Math.round(durationMs),
              statusCode,
              inflight: this.metrics.inflight,
            },
            'tls-check slow',
          )
        }
      },
      abort: () => {
        const durationMs = finish('aborted')
        if (durationMs === undefined) {
          return
        }
        this.warnWithinWindow(
          'aborted',
          {
            domain,
            domainClass,
            durationMs: Math.round(durationMs),
            inflight: this.metrics.inflight,
          },
          'tls-check aborted',
        )
      },
      fail: (err: unknown) => {
        const durationMs = finish('failed')
        if (durationMs === undefined) {
          return
        }
        this.warnWithinWindow(
          'failed',
          {
            err,
            domain,
            domainClass,
            durationMs: Math.round(durationMs),
            inflight: this.metrics.inflight,
          },
          'tls-check failed',
        )
      },
    }
  }

  /** Emit and reset the current aggregate window if there was any activity. */
  flush(): void {
    const current = this.metrics
    if (
      current.started === 0 &&
      current.completed === 0 &&
      current.aborted === 0 &&
      current.failed === 0 &&
      current.inflight === 0
    ) {
      this.eventLoopMonitor?.reset()
      return
    }

    const memoryUsage = process.memoryUsage()
    this.logger.info(
      {
        window: {
          started: current.started,
          completed: current.completed,
          aborted: current.aborted,
          failed: current.failed,
          inflight: current.inflight,
          maxInflight: current.maxInflight,
        },
        status: mapToObject(current.status),
        domainClass: mapToObject(current.domainClass),
        durationMs: summarizeDurations(current.durationsMs),
        accountLookupMs: summarizeDurations(current.accountLookupMs),
        individualLogSuppressed: mapToObject(current.individualLogSuppressed),
        eventLoopLagMs: this.readEventLoopLag(),
        memory: {
          rssMb: bytesToMiB(memoryUsage.rss),
          heapUsedMb: bytesToMiB(memoryUsage.heapUsed),
          heapTotalMb: bytesToMiB(memoryUsage.heapTotal),
          externalMb: bytesToMiB(memoryUsage.external),
        },
      },
      'tls-check summary',
    )

    this.metrics = createEmptyMetrics(current.inflight)
    this.eventLoopMonitor?.reset()
  }

  /** Stop timers and event-loop monitoring before process shutdown or tests end. */
  stop(): void {
    if (this.summaryTimer) {
      clearInterval(this.summaryTimer)
    }
    this.eventLoopMonitor?.disable()
  }

  private warnWithinWindow(
    category: IndividualLogCategory,
    fields: Record<string, unknown>,
    message: string,
  ): void {
    const emitted = this.metrics.individualLogEmitted.get(category) ?? 0
    if (emitted < this.individualLogLimitPerWindow) {
      this.metrics.individualLogEmitted.set(category, emitted + 1)
      this.logger.warn(fields, message)
      return
    }
    incrementMap(this.metrics.individualLogSuppressed, category)
  }

  private readEventLoopLag(): Record<string, number> | undefined {
    const monitor = this.eventLoopMonitor
    if (!monitor) {
      return undefined
    }
    return {
      p50: nanosecondsToMilliseconds(monitor.percentile(50)),
      p95: nanosecondsToMilliseconds(monitor.percentile(95)),
      max: nanosecondsToMilliseconds(monitor.max),
    }
  }
}

function createEmptyMetrics(inflight = 0): MutableWindowMetrics {
  return {
    started: 0,
    completed: 0,
    aborted: 0,
    failed: 0,
    inflight,
    maxInflight: inflight,
    status: new Map(),
    domainClass: new Map(),
    durationsMs: [],
    accountLookupMs: [],
    individualLogEmitted: new Map(),
    individualLogSuppressed: new Map(),
  }
}

function incrementMap<TKey>(map: Map<TKey, number>, key: TKey): void {
  map.set(key, (map.get(key) ?? 0) + 1)
}

function mapToObject<TKey extends number | string>(
  map: Map<TKey, number>,
): Record<string, number> {
  const entries = Array.from(map.entries()).map(([key, value]) => [
    String(key),
    value,
  ])
  return Object.fromEntries(entries) as Record<string, number>
}

function summarizeDurations(values: number[]): Record<string, number> {
  if (values.length === 0) {
    return { count: 0 }
  }
  const sorted = [...values].sort((a, b) => a - b)
  return {
    count: sorted.length,
    min: Math.round(sorted[0]),
    p50: Math.round(percentile(sorted, 50)),
    p95: Math.round(percentile(sorted, 95)),
    p99: Math.round(percentile(sorted, 99)),
    max: Math.round(sorted[sorted.length - 1]),
  }
}

function percentile(sorted: number[], percent: number): number {
  const index = Math.min(
    sorted.length - 1,
    Math.max(0, Math.ceil((percent / 100) * sorted.length) - 1),
  )
  return sorted[index]
}

function bytesToMiB(bytes: number): number {
  return Math.round((bytes / 1024 / 1024) * 10) / 10
}

function nanosecondsToMilliseconds(nanoseconds: number): number {
  if (!Number.isFinite(nanoseconds) || nanoseconds <= 0) {
    return 0
  }
  return Math.round((nanoseconds / 1_000_000) * 10) / 10
}
